### ISSUE TITLE
Retain Last Boundary URI in UI

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/boundary-ui#1015]
**Is your feature request related to a problem? Please describe.**
Eventually a connection to Boundary will be broken and the user will be asked to disconnect, then the user has to type in the boundary URI again:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/4521230/157288916-25fa64d7-056c-494f-9848-7c2f48cf2c61.png">

**Describe the solution you'd like**
It would be nice to retain the last connected URI autofilled in the URI field.  OR to have some clickable item representing a destination.

**Additional context**
Users aren't good at remembering long URIs.

**Comment by randallmorey** [comment]
Excellent suggestion!  We'll look into it.

**Comment by netsandbox** [comment]
If you have only one cluster, maybe #1106 would also help here.

**Comment by gsusmi** [comment]
Apologies on the delay in response. We added this to our product backlog. Watch our release announcements for further updates. Ty.
