### ISSUE TITLE
Admin UI users page serves stale content after user -> account association

### ISSUE THREAD

**Issue by johanbrandhorst** [hashicorp/boundary-ui#1096]
**Describe the bug**
The admin UI users page shows user -> account association with a gray background text. When assigning an account to a user account that previously did not have an account, the visual hint is not shown until a page reload.

**To Reproduce**
1. Create a new user
2. Create a new account
3. Associate the new account with the user.
4. Navigate to the users page. Note that the visual association is not present.
5. Reload the page. Note that the visual association is now present.

**Expected behavior**
I expect the visual user -> account association to be present after the association is completed.

**Additional context**

See recording for a visual example:

https://user-images.githubusercontent.com/6604151/166251178-fea3b1e4-bcbc-4c40-ab90-8a9d5c46da01.mov

The same thing (in reverse) is present when removing an account association from a user.

**Comment by ZedLi** [comment]
Fixed in https://github.com/hashicorp/boundary-ui/pull/1105
