### ISSUE TITLE
Filter expression not being sent in request to create a new managed group

### ISSUE THREAD

**Issue by RickyGrassmuck** [hashicorp/boundary-ui#1194]
**Describe the bug**
When attempting to add a new OIDC Managed Group, the filter expression provided in the input box is not being sent in the request to the `/v1/managed-groups` endpoint.

**To Reproduce**
1. Setup HCP Boundary
2. Connect Azure AD as an OIDC provider
3. Open the page to create a new managed group for the provider
4. Fill out the form. For the filter, I am using `"081a4544-cc93-4b17-a004-463b71812e0a" in "/token/roles"`
5. Open the Network Requests tab in the browsers developer tool.
6. Hit the save button and receive the error message
7. Check the data sent in the post request and see that the `attributes.filter` value in the JSON data is set to null.

![image](https://user-images.githubusercontent.com/17223437/179162377-e0d5cb37-e0dd-45ef-8d3d-7d62795897f3.png)

**Expected behavior**
The Filter value should be sent to boundary so that the managed group can be created

**Additional context**
This was all done on an HCP Boundary instance spun up using the official learn guide using a free tier Azure AD account.

**Comment by gsusmi** [comment]
Ty for reporting this issue! We'll look into this.

**Comment by gsusmi** [comment]
Resolved by https://github.com/hashicorp/boundary-ui/pull/1238. Fix will become available in an upcoming release.
