### ISSUE TITLE
Search & sort of targets

### ISSUE THREAD

**Issue by ReLehmann** [hashicorp/boundary-ui#1368]
**Is your feature request related to a problem? Please describe.**
Above a certain number of targets, the search for a specific one can become very time-consuming. 

**Describe the solution you'd like**
It would be nice if the filter allows a live "search"/filtering via the standard keyboard shortcut. 

**Describe alternatives you've considered**
It would already be helpful if the columns of the overview table could be sorted by header. Or at least display the entries sorted by name.

**Comment by gsusmi** [comment]
Good morning @lenny167 and thanks for trying out Boundary!

Thank you for the suggestion. We'll look into it. Be on the lookout for updates here!

**Comment by AdamBouhmad** [comment]
Hey @reza-solaris, this is something the team is actively working on.

**Comment by adriana-olszak** [comment]
@AdamBouhmad  Hey, any ETA for the search option? We are trying to automate away from Boundary UI due to this.

**Comment by AdamBouhmad** [comment]
> @AdamBouhmad Hey, any ETA for the search option? We are trying to automate away from Boundary UI due to this.

Hey @adriana-olszak -- the team is hard at work [implementing search/filtering](https://github.com/hashicorp/boundary/issues/2780) within Boundary, but we don't have an update to share publicly just yet. We'll update this thread when we have more information to share. 

We do have some exciting Boundary announcements coming out with [HashiConf](https://hashiconf.com/2023/schedule/san-francisco/), so definitely stay tuned for those.

**Comment by anando-chatterjee** [comment]
Boundary 0.15 includes new search and filtering capabilities within the Desktop Client and the CLI. Users now have the ability to locate targets and sessions by simply typing in the partial or full name or ID of the target that they are trying to connect to. Additionally, they can further narrow down the results by filtering out the scopes or session states (active, pending, or terminated). Larger result sets are paginated for improved search performance. We will also support search and filtering within Boundary's admin web GUI in a subsequent release.

Please take a peek at other exciting additions to Boundary within the latest release by reviewing [this blog post](https://www.hashicorp.com/blog/boundary-0-15-adds-new-storage-policies-and-desktop-cli-features). As always, we would really appreciate this community's feedback on any of the new feature announcements. Thank you!
