### ISSUE TITLE
Connection to Boundary fails

### ISSUE THREAD

**Issue by timm-e** [hashicorp/boundary-ui#1687]
**Describe the bug**
When connecting with boundary desktop to my cluster URL, I get a failure instead of an authentication window.

Authentication to the web interface and the CLI works fine.

**To Reproduce**
1. Start boundary desktop and enter https://boundary.inqi.essigke.net
2. Error message 
```
Something went wrong
Error
We're not sure what happened. Please contact your administrator or try again later.

```
**Expected behavior**
Authentication window should open.

**Additional context**
It is a cluster of three boundary servers behind a Amazon ELB load balancer and with Nginx to terminate SSL. The servers are running boundary v.12.1. The client Desktop Client v1.5.1 (amd64, deb)
I couldn't find anything helpful in the log files.

**Comment by randallmorey** [comment]
Hi there.  Thanks for trying Boundary and Boundary Desktop.  It looks like CORS may be disabled or misconfigured.  In order to connect to a controller, Boundary Desktop requires that CORS be enabled.  The [TCP listener documentation](https://developer.hashicorp.com/boundary/docs/configuration/listener/tcp#cors_enabled) is a good place to start.

**Comment by malnick** [comment]
@timm-e - Thanks again for trying out Boundary, can you verify whether or not this work around was successful for you?

**Comment by timm-e** [comment]
Hi,

sorry for the late reply. I was out of office for some time.

You are right, CORS was disabled, but commenting it out or enabling it 
explicitly does not help. I also tried to set cors_allowed_origins, but 
without success.  I disabled TLS and address without success. Now, the 
only thing left is:

listener "tcp" {
   purpose = "api"
   tls_disabled = true
}

My nginx configuration is striped down to:

server {
   listen 443 ssl;
   server_name boundary.inqi.essigke.net;
   ssl_certificate ...
   ssl_certificate_key ...
   location / {
     proxy_pass http://127.0.0.1:9200;
   }
}

The webinterface still works and boundary-ui still fails. Any other hints?

Thanks,

Timm

Am 15.05.23 um 17:54 schrieb Randall Morey:
