### ISSUE TITLE
can not install ember-pollster depend on package

### ISSUE THREAD

**Issue by JacobLi11** [hashicorp/boundary-ui#1804]
**Describe the bug**
https://www.npmjs.com/ 
do not have ember-pollster package
so i can not build boundary

**To Reproduce**
1. Run `yarn install`
3. See error
error Received malformed response from registry for "ember-pollster". The registry may be down.

**Comment by ZedLi** [comment]
Hey @JacobLi11,

We had an issue with the package and we're now pointing to a specific git url for this package. Can you pull the latest changes from main and try again?

**Comment by JacobLi11** [comment]
Thanks~ @ZedLi 
I success build boundary-ui,thanks~
