### ISSUE TITLE
Boundary Desktop does not show version number

### ISSUE THREAD

**Issue by shochdoerfer** [hashicorp/boundary-ui#2361]
To know if I am running the latest Boundary Desktop version, it would be great to see the version number somewhere in Boundary Desktop.

**Comment by gsusmi** [comment]
Thank you for reporting this. Sharing your platform details (macos/windows/etc. with arch variant) will help in triaging this.

**Comment by shochdoerfer** [comment]
In my case, it's Boundary Desktop for Windows. Not sure if Mac or Linux behaves differently as I don't have any devices to test that with.

**Comment by ZedLi** [comment]
Hey @shochdoerfer, thanks for the report! Unfortunately this is a known issue and we only have the ability to see the version in the mac version currently.

However, we're working on adding this functionality to windows and can update this issue when it's completed.

**Comment by ZedLi** [comment]
Hi @shochdoerfer, as part of the [v2.2.0](https://developer.hashicorp.com/boundary/install?product_intent=boundary#desktop-client) release, we added a new settings page which should now display the relevant version numbers! Let us know if you encounter any issues.
