### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by jboero** [hashicorp/boundary-ui#885]
On a fresh build in Linux the ember app tries to start but then immediately reports an error and crashes.  Not what version of libva is expected but mine worked earlier:

```
Your Ember app (or other code) in the main window has crashed.
This is a serious issue that needs to be handled and/or debugged.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[93416:1226/161547.973073:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```
vainfo:
```
$ vainfo
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      <unknown profile>               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
```

**Comment by jboero** [comment]
I think this may just be because my Node version is too new (and possibly other libraries):
```
yarn run v1.22.10
error @: The engine "node" is incompatible with this module. Expected version ">=10 <=15". Got "16.13.0"
error Commands cannot run with an incompatible environment.
```

**Comment by calcaide** [comment]
Hey @jboero 

You are getting an error because you are trying to use a node version higher than supported.
At the moment, we are just supporting LTS node versions.

That said, node `v16` is LTS and it should be supported. Also, I couldn't find in our code the `>=10 <=15` limitation, we currently have `>=12 <=17` in all our codebase.

To facilitate debugging, do you mind sharing:
What command did you run?  i.e `yarn start`.
Where did you run it? i.e. within `ui/admin`

Thanks for the contribution!

**Comment by jboero** [comment]
Hi @calcaide thanks for the tips.  I set this down for a bit but nice to pick it up again.  I noticed a few things.  The warning about node must be a red herring then:
```
WARNING: Node v16.13.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
```

I used to build RPMs for Fedora and *EL but the build has changed a bit so I'm trying to update the build.  First I just realized the deb builds require a umask of 0022 which I had more restricted.  They were breaking the build so it might be helpful output about that in build:
```
✖ Making for target: deb - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: deb
Command failed with a non-zero return code (2):
fakeroot dpkg-deb --build /tmp/electron-installer--337849-k1DzqxV8hpXC/boundary-desktop_0.0.0_amd64

dpkg-deb: error: control directory has bad permissions 750 (must be >=0755 and <=0775)
Error: Command failed with a non-zero return code (2):
fakeroot dpkg-deb --build /tmp/electron-installer--337849-k1DzqxV8hpXC/boundary-desktop_0.0.0_amd64

dpkg-deb: error: control directory has bad permissions 750 (must be >=0755 and <=0775)
    at ChildProcess.<anonymous> (/home/jboero/code/boundary-ui/ui/desktop/electron-app/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
error Command failed with exit code 1.
```
Fixed that with a temporary umask of 0022.

Then the build completes fine but I still hit the libva errors in the electron app.  Web UI runs just fine locally but I'm trying to get the electron app running again as it seems to have broken on Fedora recently.

**Comment by jboero** [comment]
Funny enough I just encountered this issue with a completely different Electron app - Signal Desktop on Mac. It listed a workaround which works for me and it works fine again :shrug: 

```
./boundary-desktop --no-sandbox
```
file:///home/jboero/Desktop/screenshot3.png

**Comment by jboero** [comment]
https://github.com/signalapp/Signal-Desktop/issues/3989

**Comment by calcaide** [comment]
The warning about using a Node version not tested against Ember CLI seems to come from internal ember tooling no been happy with your node version.

Did you pull the latest changes before running the build?

Can you describe what commands did you run and from what directories? This will help us to reproduce this issue.

Also we will appreciate some context as node version and what architecture you are running:

Do you mind to run and show the outcome of `node -v` and `node -p "process.arch"` ?

Thank you.

**Comment by jboero** [comment]
Yes I pulled the latest changes.  I've since built an SRPM spec which pulls the source and builds signed RPMs for Fedora/RPM-based distros using Fedora's build automation.  It includes Desktop links and puts the directory in /usr/share/boundary-ui/.  To run the client a binary script in /usr/bin/boundary-ui does a cd /usr/share/boundary-ui/ and runs the client with `--no-sandbox` which seems to work fine as without a sandbox Electron can see the GPU and libva devices.

https://copr.fedorainfracloud.org/coprs/boeroboy/hashicorp/build/3193055/
```
$ node -v
v16.13.2
$ node -p "process.arch"
x64
```

**Comment by calcaide** [comment]
Great work!

Thanks for investigating Boundary Desktop in Fedora and RPM. Unfortunately, we are not supporting the Boundary desktop client in other Linux distributions than Ubuntu.
If the Boundary Desktop and release engineering teams move to support this platform, we will refer back to this.
